---
- name: Remova o LXC e snapd, caso esteja instalado (o Ubuntu Cloud o possui)
  apt:
    state: absent
    pkg:
      - lxc
      - lxd
      - snapd

- name: Atualizar o sistema inteiro
  apt:
    upgrade: full

- name: Instalar o essencial da administração
  apt:
    state: latest
    pkg:
      - mc
      - htop
      - unrar
      - rar
      - zip
      - p7zip
      - curl
      - python3-certbot-nginx
      - systemd-coredump
      - gdb
 
- name: Criar usuário do sistema otsmanager
  user:
    name: otsmanager
    password: $6$e8gmLzXM.YGXKz$L5YwwV8FitP1WGZQoVTH.1mUcOyFGe7HbYxhl2jJS7a05D1BIsjxUgfxRcjTwGd9riy6w1bqfRCjIq53WN3Kh.
    update_password: on_create
    shell: /bin/bash
    groups: systemd-journal
    append: yes

- name: Selecionar editor para otsmanager
  copy:
    dest: /home/otsmanager/.selected_editor
    content: "SELECTED_EDITOR=\"/usr/bin/mcedit\""
    owner: otsmanager
    group: otsmanager

- name: Instale a configuração do shell .otsmanager
  template:
    src: templates/.otsmanager
    dest: /home/otsmanager/.otsmanager
    owner: otsmanager
    group: otsmanager
    mode: 0644

- name: Ativar arquivo de configuração do shell .otsmanager
  lineinfile:
    dest: /home/otsmanager/.bashrc
    line: . ~/.otsmanager
    regexp: ^\. ~/\.otsmanager

- name: Excluir anúncio da cloud do Ubuntu
  file:
    path: /etc/update-motd.d/51-cloudguest
    state: absent

- name: Instalar mensagem de boas-vindas
  template:
    src: templates/61-otshosting-motd
    dest: /etc/update-motd.d/61-otshosting-motd
    owner: root
    group: root
    mode: 0755
