---
- name: Instale o servidor MySQL e pacotes de backup
  apt:
    state: latest
    pkg:
      - mariadb-server
      - python3-mysqldb
      - automysqlbackup
      - MySQL-python

- name: Altere o conjunto de caracteres do MySQL para evitar o erro 1709 do MySQL
  template:
    src: templates/60-charset.cnf
    dest: /etc/mysql/mariadb.conf.d/60-charset.cnf
  when: ansible_distribution_major_version|int > 15
  notify: restart mysql

- name: Iniciar serviço Mysql
  service:
    name: mysql
    state: restarted
    enabled: true

- name: Analisar .my.cnf existente
  shell: grep -s pass /home/otsmanager/.my.cnf | sed 's/password=//'
  register: existingpass

- name: Gere uma senha aleatória do otsmanager do MySQL
  command: openssl rand -base64 18
  register: randompass
  when: not existingpass.stdout

- set_fact:
    mysql_otsmanager_pass: "{{ randompass.stdout if randompass is not skipped else existingpass.stdout }}"

- name: Definir senha do MySQL otsmanager (localhost)
  mysql_user:
    name: otsmanager
    password: "{{ mysql_otsmanager_pass }}"
    host: localhost
    priv: "*.*:ALL,GRANT"
    check_implicit_admin: yes

- name: Salve a senha do MySQL otsmanager
  template:
    src: .my.cnf
    dest: /home/otsmanager/.my.cnf
    owner: otsmanager
    group: otsmanager
    mode: 0600
  
- name: Definir senha do otsmanager do MySQL (%)
  mysql_user:
    name: otsmanager
    password: "{{ mysql_otsmanager_pass }}"
    host: "%"
    priv: "*.*:ALL,GRANT"
    check_implicit_admin: yes

- name: Verifique o nome do host
  command: hostname -f
  register: realhostname

- name: Exclua contas root do MySQL que não queremos
  mysql_user:
    name: root
    host: "{{item}}"
    state: absent
    check_implicit_admin: yes
  with_items:
    - 127.0.0.1
    - ::1
    - realhostname.stdout
    - "%"

- name: Garanta que usuários anônimos do MySQL não estejam no banco de dados
  mysql_user:
    name: ""
    host_all: yes
    state: absent
    check_implicit_admin: yes

- name: Excluir banco de dados de teste do MySQL
  mysql_db:
    name: test
    state: absent

- name: Permitir que o otsmanager acesse o diretório automysqlbackup
  file:
    path: /var/lib/automysqlbackup
    state: directory
    group: otsmanager
