---
- name: Instalar nginx
  apt:
    pkg: nginx
    state: latest

- name: Copie a configuração do nginx para o vhost padrão
  template:
    src: templates/nginx-vhost.conf
    dest: /etc/nginx/sites-available/default
  notify: restart nginx

- name: Iniciar serviço nginx
  service:
    name: nginx
    state: started
    enabled: yes
