---
- name: Instalando o debconf para definir informações pré-configuradas
  apt:
    pkg: debconf-utils

- name: Definindo as informações predefinidas phpmyadmin/dbconfig-install
  debconf:
    name: phpmyadmin
    question: phpmyadmin/dbconfig-install
    value: true
    vtype: boolean

- name: Definindo as informações predefinidas phpmyadmin/app-password-confirm
  debconf:
    name: phpmyadmin
    question: phpmyadmin/app-password-confirm
    value: ''
    vtype: password

- name: Definir informações predefinidas phpmyadmin/mysql/admin-pass
  debconf:
    name: phpmyadmin
    question: phpmyadmin/mysql/admin-pass
    value: ''
    vtype: password

- name: Definindo as informações predefinidas phpmyadmin/mysql/app-pass
  debconf:
    name: phpmyadmin
    question: phpmyadmin/mysql/app-pass
    value: ''
    vtype: password

- name: Definindo as informações predefinidas phpmyadmin/reconfigure-webserver
  debconf:
    name: phpmyadmin
    question: phpmyadmin/reconfigure-webserver
    value: ''
    vtype: multiselect

- name: Instalando o phpmyadmin
  apt:
    pkg: phpmyadmin
    state: latest

# https://stackoverflow.com/a/54454108/1447395
- name: Patch bug no Ubuntu 18.04
  replace:
    dest: /usr/share/phpmyadmin/libraries/sql.lib.php
    regexp: |
      \|\| \(count\(\$analyzed_sql_results\['select_expr'] == 1\)$
    replace: "            || ((count($analyzed_sql_results['select_expr']) == 1)\n"
