---
# journal configuração
- name: Criar /var/log/journal
  file:
    path: /var/log/journal
    state: directory
    owner: root
    group: systemd-journal
    mode: 02755

- name: Criar /etc/systemd/journald.conf.d
  file:
    path: /etc/systemd/journald.conf.d
    state: directory

- name: Instalar /etc/systemd/journald.conf.d/journald.conf
  template:
    src: systemd/journald.conf
    dest: /etc/systemd/journald.conf.d/journald.conf
    owner: root
    group: root
    mode: 0644
  notify: restart systemd-journald
